<?php

namespace k\db;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-29 at 16:52:19.
 */
class TableTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Table
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Table;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}
	
	public function testInsert() {
		
	}

}
