<?php

namespace k;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-23 at 15:25:55.
 */
class AppTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var App
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new App;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers k\App::applyConfig
	 * @todo   Implement testApplyConfig().
	 */
	public function testApplyConfig() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers k\App::__toString
	 * @todo   Implement test__toString().
	 */
	public function test__toString() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
